# Generated by Django 6.0.2 on 2026-02-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('proyecto', models.CharField(blank=True, max_length=255)),
                ('tipo_pruebas', models.CharField(blank=True, max_length=255)),
                ('responsable_solicitud', models.CharField(blank=True, max_length=255)),
                ('lider_proyecto', models.CharField(blank=True, max_length=255)),
                ('tipo_aplicacion', models.CharField(blank=True, max_length=255)),
                ('numero_version', models.CharField(blank=True, max_length=255)),
                ('extracted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
