# Generated by Django 6.0.2 on 2026-04-02 20:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('nomenclatura', models.CharField(max_length=5, unique=True, verbose_name='Nomenclatura (máx. 5 caracteres)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('proyecto', models.CharField(blank=True, max_length=255)),
                ('tipo_servicio', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_pruebas', models.CharField(blank=True, max_length=255)),
                ('responsable_solicitud', models.CharField(blank=True, max_length=255)),
                ('lider_proyecto', models.CharField(blank=True, max_length=255)),
                ('tipo_aplicacion', models.CharField(blank=True, max_length=255)),
                ('numero_version', models.CharField(blank=True, max_length=255)),
                ('funcionalidad_liberacion', models.TextField(blank=True)),
                ('detalle_cambios', models.TextField(blank=True)),
                ('justificacion_cambio', models.TextField(blank=True)),
                ('ticket_code', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('nomenclatura', models.CharField(max_length=10, unique=True, verbose_name='Nomenclatura (máx. 10 caracteres)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('puesto', models.CharField(blank=True, max_length=100, verbose_name='Puesto')),
                ('puede_generar_tickets', models.BooleanField(default=True)),
                ('puede_ver_todos_tickets', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cliente_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.cliente', verbose_name='Cliente asociado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Proyecto')),
                ('nomenclatura', models.CharField(help_text='Abreviatura del proyecto (ej: B2C, DLW, SPM, etc.)', max_length=10, verbose_name='Nomenclatura del Proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='extractor.cliente', verbose_name='Cliente')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['cliente', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código del Ticket')),
                ('jira_issue_key', models.CharField(blank=True, help_text='Ej: QA01-123', max_length=50, null=True, verbose_name='Clave de incidencia Jira')),
                ('jira_issue_url', models.URLField(blank=True, null=True, verbose_name='URL de incidencia Jira')),
                ('fecha_sincronizacion_jira', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de sincronización con Jira')),
                ('empresa_code', models.CharField(default='BID', max_length=10, verbose_name='Código Empresa')),
                ('tipo_servicio_code', models.CharField(max_length=10, verbose_name='Código Tipo Servicio')),
                ('funcion_code', models.CharField(max_length=20, verbose_name='Código Función')),
                ('version_code', models.CharField(max_length=10, verbose_name='Código Versión')),
                ('cliente_code', models.CharField(max_length=10, verbose_name='Código Cliente')),
                ('proyecto_code', models.CharField(max_length=10, verbose_name='Código Proyecto')),
                ('consecutivo', models.IntegerField(verbose_name='Consecutivo')),
                ('responsable_solicitud', models.CharField(blank=True, max_length=255, verbose_name='Responsable')),
                ('lider_proyecto', models.CharField(blank=True, max_length=255, verbose_name='Líder del Proyecto')),
                ('numero_version', models.CharField(blank=True, max_length=255, verbose_name='Número de Versión')),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='GENERADO', max_length=20, verbose_name='Estado del Ticket')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.cliente', verbose_name='Cliente')),
                ('excel_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extractor.exceldata', verbose_name='Datos del Excel')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.proyecto', verbose_name='Proyecto')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_ticket', models.BooleanField(db_index=True, default=False, help_text='Indica si la solicitud tiene un ticket asociado', verbose_name='¿Tiene ticket?')),
                ('fecha_asociacion_ticket', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asociación con ticket')),
                ('nombre_archivo', models.CharField(blank=True, db_index=True, help_text='Formato: BID-PMC-FOR-00017-nomenclatura_AAAAMMDD-XXX.xlsx', max_length=255, verbose_name='Nombre del archivo generado')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('hora_solicitud', models.TimeField(verbose_name='Hora de Solicitud')),
                ('tipo_servicio_code', models.CharField(choices=[('PRU', 'Pruebas'), ('EST', 'Estimación'), ('G&A', 'Gestión y administración')], max_length=3, verbose_name='Tipo de Servicio')),
                ('area_solicitante', models.CharField(blank=True, max_length=100, verbose_name='Área Solicitante')),
                ('numero_version', models.CharField(blank=True, max_length=50, verbose_name='Número de Versión')),
                ('responsable_solicitud', models.CharField(blank=True, max_length=255, verbose_name='Responsable de Solicitud')),
                ('lider_proyecto', models.CharField(blank=True, max_length=255, verbose_name='Líder de Proyecto')),
                ('tipo_aplicacion', models.CharField(blank=True, choices=[('Portal WEB', 'Portal WEB'), ('App - Android', 'App - Android'), ('App - IOS', 'App - IOS'), ('App - Android & IOS', 'App - Android & IOS'), ('Servicio', 'Servicio'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Aplicación')),
                ('funcionalidad_liberacion', models.TextField(blank=True, verbose_name='Funcionalidad de la liberación')),
                ('detalle_cambios', models.TextField(blank=True, verbose_name='Detalle de los cambios')),
                ('justificacion_cambio', models.TextField(blank=True, verbose_name='Justificación del cambio')),
                ('puntos_considerar', models.TextField(blank=True, verbose_name='Puntos a Considerar')),
                ('pendientes', models.TextField(blank=True, verbose_name='Pendientes')),
                ('insumos', models.TextField(blank=True, verbose_name='Insumos Requeridos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.CharField(blank=True, max_length=100, verbose_name='Creado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extractor.cliente', verbose_name='Cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extractor.proyecto', verbose_name='Proyecto')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud', to='extractor.ticket', verbose_name='Ticket Asociado')),
                ('tipo_prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extractor.tiposervicio', verbose_name='Tipo de Pruebas')),
            ],
            options={
                'verbose_name': 'Solicitud de Pruebas',
                'verbose_name_plural': 'Solicitudes de Pruebas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['codigo'], name='extractor_t_codigo_3676af_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='extractor_t_estado_0342e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['fecha_creacion'], name='extractor_t_fecha_c_f1b9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpruebas',
            index=models.Index(fields=['fecha_solicitud'], name='extractor_s_fecha_s_c70477_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpruebas',
            index=models.Index(fields=['cliente', 'proyecto'], name='extractor_s_cliente_cba58a_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpruebas',
            index=models.Index(fields=['tiene_ticket'], name='extractor_s_tiene_t_2505da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('cliente', 'nombre')},
        ),
    ]
