# Generated by Django 6.0.2 on 2026-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='detalle_cambios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='funcionalidad_liberacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='justificacion_cambio',
            field=models.TextField(blank=True),
        ),
    ]
