# Generated by Django 6.0.2 on 2026-04-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_ticket_asignado_a_ticket_comentarios_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('GENERADO', 'Generado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='GENERADO', max_length=20, verbose_name='Estado del Ticket'),
        ),
    ]
