# Generated by Django 6.0.2 on 2026-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('nomenclatura', models.CharField(max_length=10, unique=True, verbose_name='Nomenclatura (máx. 10 caracteres)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
