# Generated by Django 6.0.2 on 2026-04-06 23:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dictamen_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Dictamen PDF'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dictamen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del dictamen'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evidencia_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Evidencia de Pruebas PDF'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evidencia_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la evidencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_subida_dictamen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida del dictamen'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_subida_evidencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida de evidencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
    ]
