# Generated by Django 6.0.2 on 2026-04-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_ticket_dictamen_pdf_ticket_dictamen_url_and_more'),
    ]

    operations = [
        # ⚠️ ELIMINADO: migrations.AddField para 'nombre' en Ticket (ya existe)
        
        # ✅ Solo mantener este
        migrations.AddField(
            model_name='usuario',
            name='es_lider_pruebas',
            field=models.BooleanField(default=False, verbose_name='¿Es líder de pruebas?'),
        ),
    ]