# Generated by Django 6.0.2 on 2026-02-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nomenclatura',
            field=models.CharField(default='', help_text='Abreviatura del proyecto (ej: B2C, DLW, SPM, etc.)', max_length=10, verbose_name='Nomenclatura del Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
    ]
