# Generated by Django 6.0.2 on 2026-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_proyecto_nomenclatura_proyecto_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='tipo_servicio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
