# Generated by Django 6.0.2 on 2026-02-10 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_exceldata_ticket_code_exceldata_tipo_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código del Ticket')),
                ('empresa_code', models.CharField(default='BID', max_length=10, verbose_name='Código Empresa')),
                ('tipo_servicio_code', models.CharField(max_length=10, verbose_name='Código Tipo Servicio')),
                ('funcion_code', models.CharField(max_length=20, verbose_name='Código Función')),
                ('version_code', models.CharField(max_length=10, verbose_name='Código Versión')),
                ('cliente_code', models.CharField(max_length=10, verbose_name='Código Cliente')),
                ('proyecto_code', models.CharField(max_length=10, verbose_name='Código Proyecto')),
                ('consecutivo', models.IntegerField(verbose_name='Consecutivo')),
                ('responsable_solicitud', models.CharField(blank=True, max_length=255, verbose_name='Responsable')),
                ('lider_proyecto', models.CharField(blank=True, max_length=255, verbose_name='Líder del Proyecto')),
                ('numero_version', models.CharField(blank=True, max_length=255, verbose_name='Número de Versión')),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='GENERADO', max_length=20, verbose_name='Estado del Ticket')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.cliente', verbose_name='Cliente')),
                ('excel_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extractor.exceldata', verbose_name='Datos del Excel')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.proyecto', verbose_name='Proyecto')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo'], name='extractor_t_codigo_3676af_idx'), models.Index(fields=['estado'], name='extractor_t_estado_0342e4_idx'), models.Index(fields=['fecha_creacion'], name='extractor_t_fecha_c_f1b9b3_idx')],
            },
        ),
    ]
