# Generated by Django 6.0.2 on 2026-03-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('hora_solicitud', models.TimeField(verbose_name='Hora de Solicitud')),
                ('tipo_servicio_code', models.CharField(choices=[('PRU', 'Pruebas'), ('EST', 'Estimación'), ('G&A', 'Gestión y administración')], max_length=3, verbose_name='Tipo de Servicio')),
                ('area_solicitante', models.CharField(blank=True, max_length=50, verbose_name='Área Solicitante')),
                ('numero_version', models.CharField(blank=True, max_length=50, verbose_name='Número de Versión')),
                ('responsable_solicitud', models.CharField(blank=True, max_length=255, verbose_name='Responsable de Solicitud')),
                ('lider_proyecto', models.CharField(blank=True, max_length=255, verbose_name='Líder de Proyecto')),
                ('tipo_aplicacion', models.CharField(blank=True, choices=[('Portal WEB', 'Portal WEB'), ('App - Android', 'App - Android'), ('App - IOS', 'App - IOS'), ('App - Android & IOS', 'App - Android & IOS'), ('Servicio', 'Servicio'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Aplicación')),
                ('funcionalidad_liberacion', models.TextField(blank=True, verbose_name='Funcionalidad de la liberación')),
                ('detalle_cambios', models.TextField(blank=True, verbose_name='Detalle de los cambios')),
                ('justificacion_cambio', models.TextField(blank=True, verbose_name='Justificación del cambio')),
                ('puntos_considerar', models.TextField(blank=True, verbose_name='Puntos a Considerar')),
                ('pendientes', models.TextField(blank=True, verbose_name='Pendientes')),
                ('insumos', models.TextField(blank=True, verbose_name='Insumos Requeridos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.CharField(blank=True, max_length=100, verbose_name='Creado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extractor.cliente', verbose_name='Cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extractor.proyecto', verbose_name='Proyecto')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud', to='extractor.ticket', verbose_name='Ticket Asociado')),
                ('tipo_prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extractor.tiposervicio', verbose_name='Tipo de Pruebas')),
            ],
            options={
                'verbose_name': 'Solicitud de Pruebas',
                'verbose_name_plural': 'Solicitudes de Pruebas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_solicitud'], name='extractor_s_fecha_s_c70477_idx'), models.Index(fields=['cliente', 'proyecto'], name='extractor_s_cliente_cba58a_idx')],
            },
        ),
    ]
