# Generated by Django 6.0.2 on 2026-03-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0009_solicitudpruebas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpruebas',
            name='nombre_archivo',
            field=models.CharField(blank=True, help_text='Formato: BID-PMC-FOR-00017-nomenclatura_AAAAMMDD-XXX.xlsx', max_length=255, verbose_name='Nombre del archivo generado'),
        ),
    ]
