# Generated by Django 6.0.2 on 2026-03-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0010_solicitudpruebas_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpruebas',
            name='fecha_asociacion_ticket',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asociación con ticket'),
        ),
        migrations.AddField(
            model_name='solicitudpruebas',
            name='tiene_ticket',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si la solicitud tiene un ticket asociado', verbose_name='¿Tiene ticket?'),
        ),
        migrations.AddIndex(
            model_name='solicitudpruebas',
            index=models.Index(fields=['tiene_ticket'], name='extractor_s_tiene_t_2505da_idx'),
        ),
    ]
