# Generated by Django 6.0.2 on 2026-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0011_solicitudpruebas_fecha_asociacion_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_sincronizacion_jira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de sincronización con Jira'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='jira_issue_key',
            field=models.CharField(blank=True, help_text='Ej: QA01-123', max_length=50, null=True, verbose_name='Clave de incidencia Jira'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='jira_issue_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de incidencia Jira'),
        ),
        migrations.AlterField(
            model_name='solicitudpruebas',
            name='area_solicitante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Área Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitudpruebas',
            name='nombre_archivo',
            field=models.CharField(blank=True, db_index=True, help_text='Formato: BID-PMC-FOR-00017-nomenclatura_AAAAMMDD-XXX.xlsx', max_length=255, verbose_name='Nombre del archivo generado'),
        ),
    ]
