# Generated by Django 6.0.2 on 2026-04-02 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: TC-001', max_length=50)),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('precondiciones', models.TextField(blank=True, help_text='Condiciones que deben cumplirse antes de ejecutar')),
                ('pasos', models.JSONField(default=list, help_text='Lista de pasos a seguir')),
                ('resultados_esperados', models.JSONField(default=list, help_text='Resultados esperados por cada paso')),
                ('datos_prueba', models.JSONField(blank=True, default=dict, help_text='Datos necesarios para la prueba')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('modificado', 'Modificado')], default='borrador', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractor.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='extractor.solicitudpruebas')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='extractor.ticket')),
            ],
            options={
                'verbose_name': 'Caso de Prueba',
                'verbose_name_plural': 'Casos de Prueba',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('bloqueado', 'Bloqueado'), ('no_aplicable', 'No Aplicable'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('evidencias', models.JSONField(blank=True, default=list, help_text='URLs o rutas de evidencias')),
                ('tiempo_ejecucion', models.DurationField(blank=True, help_text='Tiempo total de ejecución', null=True)),
                ('entorno', models.CharField(blank=True, help_text='Entorno donde se ejecutó', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caso_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='ia_agent.casoprueba')),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Prueba',
                'verbose_name_plural': 'Ejecuciones de Pruebas',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('fuente', models.CharField(choices=[('ticket', 'Ticket'), ('solicitud', 'Solicitud de Pruebas'), ('url', 'URL'), ('texto', 'Texto Libre')], max_length=20)),
                ('url_origen', models.URLField(blank=True, null=True)),
                ('contenido_extraido', models.TextField(help_text='Contenido extraído de la fuente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='extractor.cliente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='extractor.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='extractor.solicitudpruebas')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='extractor.ticket')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='extractor.tiposervicio')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='casoprueba',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_prueba', to='ia_agent.requerimiento'),
        ),
    ]
